package com.luculent.net.springboot.mapper;

import com.luculent.net.springboot.model.Student;
import org.apache.ibatis.annotations.Mapper;

//@Mapper
/*
* @Mapper注解是mabatis扫描mapper接口
* @MapperScan("com.luculent.net.springboot.mapper")可以放在启动类上  ()里边指的是扫描包名下的类
* */
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 17 17:56:58 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 17 17:56:58 CST 2022
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 17 17:56:58 CST 2022
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 17 17:56:58 CST 2022
     */
    Student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 17 17:56:58 CST 2022
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Thu Mar 17 17:56:58 CST 2022
     */
    int updateByPrimaryKey(Student record);
}